[package]
name = "blitzlicht"
version = "0.1.0"
authors = ["Tom Ward <tom@popdog.net>"]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "1.3.0"
ansi_term = "0.9"
rand = "0.6"
clap = "2.33"
